# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameBox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GameBox
  pod 'Alamofire', '~> 5.6'
pod 'Kingfisher', '~> 6.3.1'
pod 'DropDown', '~> 2.3'
pod 'Cosmos', '~> 23.0'
pod 'NVActivityIndicatorView'

end
